# Site title and subtitle. This is used in _includes/header.html
title: 'Seravo.com Docs'
subtitle: 'Documentation for WordPress Developers'

# Titile to show in footer
name: Seravo.com

# Link to Github repo
# This is used in editing links
github:
    repo: Seravo/docs

# Seravo.com/docs entity
google_analytics_id: 'UA-53086901-9'

# Site verification for webmasters
google_site_verification: "urAsJ1u3OTw8C7-KQnc2GxU7rJb7i4DAbbPxUv-eT9k"

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://seravo.com'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/docs'

# This is used in <meta> og fields
siteurl: https://seravo.com/docs

# Use sass from assets folder
sass:
  sass_dir: /assets/_sass
  style: :compressed

# Additional gems to use
plugins:
  - jekyll-sitemap # Generates sitemaps for Google

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin','CNAME', 'README.md']

# Path to subpages, ordered by 'sequence' in navigation
collections_dir: pages

# Page categories
collections:
  get-started:
    title: "Get Started"
    output: true
    permalink: /:collection/:name/
    sequence: 1
    searchable: true
  configuration:
    title: "Configuration"
    output: true
    permalink: /:collection/:name/
    sequence: 2
    searchable: true
  tests:
    title: "Tests"
    output: true
    permalink: /:collection/:name/
    sequence: 3
    searchable: true
  development:
    title: "Development"
    output: true
    permalink: /:collection/:name/
    sequence: 4
    searchable: true
  deployment:
    title: "Deployment"
    output: true
    permalink: /:collection/:name/
    sequence: 5
    searchable: true
  management:
    title: "Management"
    output: true
    permalink: /:collection/:name/
    sequence: 6
    searchable: true
  man:
    title: "Man pages"
    output: true
    permalink: /:collection/:name/
    searchable: true

highlighter: rouge

# Use the kramdown Markdown renderer
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
